### ISSUE TITLE
Starting the Bot at boot (Raspberry Pi)

### ISSUE THREAD

**Issue by phrankme** [RobinCPel/Battlefield-V-Stat-Checker#1]
Nice work! I am really interested in using your bot but don’t know how to install it. 

Got Java 9 on my Raspi 2 and downloaded your files. I would really appreciate it if you could add next steps for compile (install d4j??) and how to execute your tool to your readme. 

Error message when using gradle is:
> pi@Eggman:~/Battlefield-V-Stat-Checker-1.0.0/Battlefield V Stat Checker $ gradle                                            WARNING: An illegal reflective access operation has occurred  WARNING: Illegal reflective access by org.gradle.internal.reflect.JavaMethod (file:/usr/share/gradle/lib/gradle-base-services-3.2.1.jar) to method java.lang.ClassLoader.getPackages()    WARNING: Please consider reporting this to the maintainers of org.gradle.internal.reflect.JavaMethod                        WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations                       WARNING: All illegal access operations will be denied in a future release                                                                                                                 
FAILURE: Build failed with an exception.                                                                                    * Where:                                                      Build file '/home/pi/Battlefield-V-Stat-Checker-1.0.0/Battlefield V Stat Checker/build.gradle' line: 3                                                                                    * What went wrong:                                            An exception occurred applying plugin request [id: 'org.jetbrains.kotlin.jvm', version: '1.3.10']                           
Failed to apply plugin [id 'org.jetbrains.kotlin.jvm']         > Could not generate a proxy class for class org.jetbrains.kotlin.gradle.dsl.KotlinJvmProjectExtension.                                                                                * Try:                                                        Run with --stacktrace option to get the stack trace. Run with 
--info or --debug option to get more log output.

**Comment by RobinCPel** [comment]
Dear Phrankme, 
First of all, thanks for checking out my Discord bot! 
And now for your issue, do you insist on compiling it yourself? If not, there is a (zipped) .jar located in [the releases folder](https://github.com/RobinCPel/Battlefield-V-Stat-Checker/tree/master/Releases). 
If you download this jar file to your Raspberry Pi and run it like "java -jar JARNAME" it _should_ work fine.

**Comment by phrankme** [comment]
Hi RobinCPel,

thank you, too easy! I searched for the .jar but didn't realise realise it was in that zip. 
Now I can easily start it. 

One more issue you maybe can help me with:
Tried to autostart the bot on my pi. Unfortunately I always receive this error (tried it via systemd and rc.local). Any ideas?

`
Dez 05 09:59:47 Eggman java[2292]: [Mi 05 Dez 2018] [09:59:47.155 UTC] [main@static]:           Booting
Dez 05 09:59:47 Eggman java[2292]: [Mi 05 Dez 2018] [09:59:47.403 UTC] [BotBooter@1961c42]:           TokeFile found! Reading content...
Dez 05 09:59:47 Eggman java[2292]: org.json.JSONException: A JSONObject text must begin with '{' at 0 [character 1 line 1]
Dez 05 09:59:47 Eggman java[2292]:         at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
Dez 05 09:59:47 Eggman java[2292]:         at org.json.JSONObject.<init>(JSONObject.java:215)
Dez 05 09:59:47 Eggman java[2292]:         at org.json.JSONObject.<init>(JSONObject.java:399)
Dez 05 09:59:47 Eggman java[2292]:         at com.robinpel.battlefieldv_statchecker.core.BotBooter.loadTokenFile(Main.kt:70)
Dez 05 09:59:47 Eggman java[2292]:         at com.robinpel.battlefieldv_statchecker.core.BotBooter.loadTokenFile$default(Main.kt:51)
Dez 05 09:59:47 Eggman java[2292]:         at com.robinpel.battlefieldv_statchecker.core.BotBooter.loadToken(Main.kt:77)
Dez 05 09:59:47 Eggman java[2292]:         at com.robinpel.battlefieldv_statchecker.core.Main.main(Main.kt:15)
`

**Comment by RobinCPel** [comment]
Is your bot-token.json file correct? It should look something like this: 
```
{
    "token": "NTE3QQQQQQQQQQQQQQQQQQQQ.QQQQQQ.QQQQQQQQQQQQQQQQQQQQQ-QQQQQ"
}
```

**Comment by phrankme** [comment]
Yep, it is. I can start the boot via "java -jar filename.jar" but not via systemd.

**Comment by RobinCPel** [comment]
I got the bot to start immediately when the Pi boots using the following code in rc.local: 
```bash
#!/bin/sh -e

# Discord Bots
/home/pi/Discord/start_discord_bots.sh &

exit 0
```

And for my own convenience I have written this little script that gets executed from rc.local (as seen above): 
```bash
#!/bin/bash
# Script used to run my discord bots

echo "Starting the BFVStat Bot"
cd /home/pi/Discord/BFVStats
nohup java -jar Battlefield\ V\ Stat\ Checker-1.0.jar &

echo "Done!"
```

I have not tried it with systemd since I am not familiar with it 😅

**Comment by phrankme** [comment]
Cool! That works now! Guess the problem was, that I did not specify the folder first.

Many thanks to you! Good work!
