### ISSUE TITLE
"Could not retrieve the stats" error, even with the example name in the README.md

### ISSUE THREAD

**Issue by mirihara** [RobinCPel/Battlefield-V-Stat-Checker#2]
When I added the bot into my server and type'd the command "!bfvstats Mirihara" or "!bfvstats RobinxCP" (as shown in the [REAMDE.md#the-bot-in-action](../tree/master/README.md#the-bot-in-action)), it won't track the stats of bf V.

**Comment by RobinCPel** [comment]
Version 1.1.0 has been released! You can download it [here](../tree/master/Releases).
Be sure to let me know if this solves your problem!

**Comment by mirihara** [comment]
thank you very much ! it's working perfectly fine and my discord channel users loved it.

**Comment by RobinCPel** [comment]
Feel free to host it!

**Comment by RobinCPel** [comment]
If you are satisfied with the answer(s), I would recommend closing the issue! 😉
