### ISSUE TITLE
No Playstation Network Support

### ISSUE THREAD

**Issue by Nemo278** [RobinCPel/Battlefield-V-Stat-Checker#4]
Hello
Unfortunately, the bot is only for Pc: O (How can you rewrite that he goes for the Playstation Network too?

**Comment by Nemo278** [comment]
please help me that it also goes to retrieve the Playstation network @RobinCPel

**Comment by RobinCPel** [comment]
The upcoming week I'll probably have some spare time, I'll see what I can do for you!

**Comment by Nemo278** [comment]
Hello
Thanks for the answer . My Psn Nick is Nemo__78 that's 2 underscores. I want to run the bot itself then on a PI: O) Currently he runs but only for PC

**Comment by RobinCPel** [comment]
Version 1.2.0 has been released! It Includes support for Playstation Network and Xbox Live. 
If you want to run the bot on a Raspberry Pi you could use this command (while also in the same folder): 
```
nohup java -jar Battlefield\ V\ Stat\ Checker-1.2.0.jar &
```

[This issue](https://github.com/RobinCPel/Battlefield-V-Stat-Checker/issues/1) might be helpful if you are looking into how you can start the bot when the Raspberry Pi boots!
